steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - ops/cloudrun/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPO: social-agent
  _IMAGE: social-agent
  _TAG: staging
