#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_ENV_FILE="${1:-${SCRIPT_DIR}/../cloudrun/deploy.env}"

if [[ ! -f "${DEPLOY_ENV_FILE}" ]]; then
  echo "Missing deploy env file: ${DEPLOY_ENV_FILE}"
  exit 1
fi

if ! command -v gcloud >/dev/null 2>&1; then
  echo "gcloud CLI not found."
  exit 1
fi

set -a
source "${DEPLOY_ENV_FILE}"
set +a

: "${PROJECT_ID:?PROJECT_ID is required in deploy env}"
: "${CONFIRM_PROJECT_ID:?CONFIRM_PROJECT_ID is required in deploy env}"
: "${SERVICE_NAME:?SERVICE_NAME is required in deploy env}"

if [[ "${PROJECT_ID}" != "${CONFIRM_PROJECT_ID}" ]]; then
  echo "Safety stop: CONFIRM_PROJECT_ID must match PROJECT_ID."
  echo "PROJECT_ID=${PROJECT_ID}"
  echo "CONFIRM_PROJECT_ID=${CONFIRM_PROJECT_ID}"
  exit 1
fi

ACTIVE_ACCOUNT="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -n1 || true)"
if [[ -z "${ACTIVE_ACCOUNT}" ]]; then
  echo "No active gcloud account. Run: gcloud auth login"
  exit 1
fi

sanitize_name() {
  local value="$1"
  value="${value//-/_}"
  echo "${value}" | tr -cd '[:alnum:]_'
}

SERVICE_SLUG="$(sanitize_name "${SERVICE_NAME}")"
METRIC_PREFIX="social_agent_${SERVICE_SLUG}"
DASHBOARD_NAME="Social Agent - ${SERVICE_NAME}"
DASHBOARDS_DIR="${SCRIPT_DIR}/dashboards"
ALERTS_DIR="${SCRIPT_DIR}/alerts"
mkdir -p "${DASHBOARDS_DIR}" "${ALERTS_DIR}"

EVENTS_METRIC="${METRIC_PREFIX}_events_received"
REDDIT_METRIC="${METRIC_PREFIX}_reddit_webhooks"
META_METRIC="${METRIC_PREFIX}_meta_webhooks"
ERRORS_METRIC="${METRIC_PREFIX}_errors"
DLQ_METRIC="${METRIC_PREFIX}_dlq_events"
POLICY_BLOCKS_METRIC="${METRIC_PREFIX}_policy_blocks"

upsert_log_metric() {
  local metric_name="$1"
  local metric_description="$2"
  local metric_filter="$3"

  if gcloud logging metrics describe "${metric_name}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
    gcloud logging metrics update "${metric_name}" \
      --description="${metric_description}" \
      --log-filter="${metric_filter}" \
      --project "${PROJECT_ID}" >/dev/null
    echo "Updated metric: ${metric_name}"
  else
    gcloud logging metrics create "${metric_name}" \
      --description="${metric_description}" \
      --log-filter="${metric_filter}" \
      --project "${PROJECT_ID}" >/dev/null
    echo "Created metric: ${metric_name}"
  fi
}

echo "Creating/updating log-based metrics for service ${SERVICE_NAME}..."
upsert_log_metric \
  "${EVENTS_METRIC}" \
  "Webhook events received by ${SERVICE_NAME}" \
  "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${SERVICE_NAME}\" AND textPayload:\"EVENT:\""

upsert_log_metric \
  "${REDDIT_METRIC}" \
  "Reddit webhook events received by ${SERVICE_NAME}" \
  "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${SERVICE_NAME}\" AND textPayload:\"EVENT: reddit_webhook_received\""

upsert_log_metric \
  "${META_METRIC}" \
  "Meta webhook events received by ${SERVICE_NAME}" \
  "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${SERVICE_NAME}\" AND textPayload:\"EVENT: meta_webhook_received\""

upsert_log_metric \
  "${ERRORS_METRIC}" \
  "Error logs emitted by ${SERVICE_NAME}" \
  "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${SERVICE_NAME}\" AND severity>=ERROR"

upsert_log_metric \
  "${DLQ_METRIC}" \
  "DLQ entries generated by ${SERVICE_NAME}" \
  "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${SERVICE_NAME}\" AND textPayload:\"sent to DLQ\""

upsert_log_metric \
  "${POLICY_BLOCKS_METRIC}" \
  "Policy blocks in ${SERVICE_NAME}" \
  "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${SERVICE_NAME}\" AND textPayload:\"High risk action requires human escalation\""

dashboard_file="${DASHBOARDS_DIR}/${SERVICE_NAME}.dashboard.json"
cat > "${dashboard_file}" <<EOF
{
  "displayName": "${DASHBOARD_NAME}",
  "mosaicLayout": {
    "columns": 12,
    "tiles": [
      {
        "xPos": 0,
        "yPos": 0,
        "width": 6,
        "height": 4,
        "widget": {
          "title": "Webhook Events (rate)",
          "xyChart": {
            "dataSets": [
              {
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "filter": "metric.type=\\"logging.googleapis.com/user/${EVENTS_METRIC}\\"",
                    "aggregation": {
                      "alignmentPeriod": "60s",
                      "perSeriesAligner": "ALIGN_RATE"
                    }
                  }
                },
                "plotType": "LINE"
              }
            ],
            "yAxis": {
              "label": "events/s",
              "scale": "LINEAR"
            }
          }
        }
      },
      {
        "xPos": 6,
        "yPos": 0,
        "width": 6,
        "height": 4,
        "widget": {
          "title": "Error Logs (sum)",
          "xyChart": {
            "dataSets": [
              {
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "filter": "metric.type=\\"logging.googleapis.com/user/${ERRORS_METRIC}\\"",
                    "aggregation": {
                      "alignmentPeriod": "60s",
                      "perSeriesAligner": "ALIGN_SUM"
                    }
                  }
                },
                "plotType": "LINE"
              }
            ],
            "yAxis": {
              "label": "errors/min",
              "scale": "LINEAR"
            }
          }
        }
      },
      {
        "xPos": 0,
        "yPos": 4,
        "width": 6,
        "height": 4,
        "widget": {
          "title": "DLQ Events (sum)",
          "xyChart": {
            "dataSets": [
              {
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "filter": "metric.type=\\"logging.googleapis.com/user/${DLQ_METRIC}\\"",
                    "aggregation": {
                      "alignmentPeriod": "60s",
                      "perSeriesAligner": "ALIGN_SUM"
                    }
                  }
                },
                "plotType": "STACKED_BAR"
              }
            ],
            "yAxis": {
              "label": "dlq",
              "scale": "LINEAR"
            }
          }
        }
      },
      {
        "xPos": 6,
        "yPos": 4,
        "width": 6,
        "height": 4,
        "widget": {
          "title": "Policy Blocks (sum)",
          "xyChart": {
            "dataSets": [
              {
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "filter": "metric.type=\\"logging.googleapis.com/user/${POLICY_BLOCKS_METRIC}\\"",
                    "aggregation": {
                      "alignmentPeriod": "60s",
                      "perSeriesAligner": "ALIGN_SUM"
                    }
                  }
                },
                "plotType": "STACKED_BAR"
              }
            ],
            "yAxis": {
              "label": "blocks",
              "scale": "LINEAR"
            }
          }
        }
      }
    ]
  }
}
EOF

existing_dashboard="$(gcloud monitoring dashboards list \
  --project "${PROJECT_ID}" \
  --filter="displayName=\"${DASHBOARD_NAME}\"" \
  --format='value(name)' | head -n1 || true)"

if [[ -n "${existing_dashboard}" ]]; then
  gcloud monitoring dashboards update "${existing_dashboard}" \
    --project "${PROJECT_ID}" \
    --config-from-file "${dashboard_file}" >/dev/null
  echo "Updated dashboard: ${DASHBOARD_NAME}"
else
  gcloud monitoring dashboards create \
    --project "${PROJECT_ID}" \
    --config-from-file "${dashboard_file}" >/dev/null
  echo "Created dashboard: ${DASHBOARD_NAME}"
fi

create_alert_policy() {
  local display_name="$1"
  local metric_name="$2"
  local threshold="$3"
  local duration="$4"

  if ! gcloud alpha monitoring policies list --project "${PROJECT_ID}" >/dev/null 2>&1; then
    echo "gcloud alpha monitoring policies unavailable. Skipping alerts setup."
    return 1
  fi

  local existing_policy
  existing_policy="$(gcloud alpha monitoring policies list \
    --project "${PROJECT_ID}" \
    --filter="displayName=\"${display_name}\"" \
    --format='value(name)' | head -n1 || true)"

  if [[ -n "${existing_policy}" ]]; then
    echo "Alert policy already exists: ${display_name}"
    return 0
  fi

  local policy_slug
  policy_slug="$(echo "${display_name,,}" | tr ' ' '-' | tr -cd '[:alnum:]_-')"
  local policy_file="${ALERTS_DIR}/${policy_slug}.json"
  cat > "${policy_file}" <<EOF
{
  "displayName": "${display_name}",
  "documentation": {
    "content": "Generated by ops/observability/setup_observability.sh",
    "mimeType": "text/markdown"
  },
  "combiner": "OR",
  "conditions": [
    {
      "displayName": "${display_name} condition",
      "conditionThreshold": {
        "filter": "metric.type=\\"logging.googleapis.com/user/${metric_name}\\"",
        "comparison": "COMPARISON_GT",
        "thresholdValue": ${threshold},
        "duration": "${duration}s",
        "trigger": {
          "count": 1
        },
        "aggregations": [
          {
            "alignmentPeriod": "${duration}s",
            "perSeriesAligner": "ALIGN_SUM"
          }
        ]
      }
    }
  ],
  "enabled": true
}
EOF

  gcloud alpha monitoring policies create \
    --project "${PROJECT_ID}" \
    --policy-from-file "${policy_file}" >/dev/null
  echo "Created alert policy: ${display_name}"
}

echo "Creating baseline alert policies..."
create_alert_policy "Social Agent ${SERVICE_NAME} - Error burst" "${ERRORS_METRIC}" 5 300 || true
create_alert_policy "Social Agent ${SERVICE_NAME} - DLQ growth" "${DLQ_METRIC}" 3 300 || true
create_alert_policy "Social Agent ${SERVICE_NAME} - Policy blocks high" "${POLICY_BLOCKS_METRIC}" 5 300 || true

echo "Observability setup complete."
echo "Dashboard spec file: ${dashboard_file}"
echo "Alert policy specs directory: ${ALERTS_DIR}"
